[versions]
longview = "0.4.0"

minecraft = "26.1-snapshot-10"

fabric_loom = "1.15.3"
fabric_loader = "0.18.4"

fabric_api = "0.143.6+26.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

[plugins]
fabric_loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric_loom" }