[versions]
longview = "0.2.0"

minecraft = "26.1-snapshot-9"

fabric_loom = "1.15.3"
fabric_loader = "0.18.4"

fabric_api = "0.143.5+26.1"
wrench_wrapper = "0.8.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
wrench_wrapper_api_fabric = { module = "page.langeweile.wrench_wrapper:api_fabric", version.ref = "wrench_wrapper" }
wrench_wrapper_api_neoforge = { module = "page.langeweile.wrench_wrapper:api_neoforge", version.ref = "wrench_wrapper" }
wrench_wrapper_impl = { module = "page.langeweile.wrench_wrapper:impl", version.ref = "wrench_wrapper" }

[bundles]
wrench_wrapper_fabric = ["wrench_wrapper_api_fabric", "wrench_wrapper_impl"]
wrench_wrapper_neoforge = ["wrench_wrapper_api_neoforge", "wrench_wrapper_impl"]

[plugins]
fabric_loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric_loom" }